
server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 20
  tomcat.uri-encoding: UTF-8
  spring.session.store-type: none


spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/news?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    database: 1
#    host: 192.168.3.124
#    port: 6379
#    timeout: 5000

#  http:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
#      enabled: true
#    encoding:
#      charset: utf-8







mybatis:
  # mybatis配置
  # 配置映射类所在包名
  type-aliases-package: com.pb.news.entity
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations:
       - mapping/*.xml
       - mapping/vo/*.xml
#      - mapping/vo/*.xml

#redis:
#  #redis配置
#  spring.redis.database: 1
#  spring.redis.host: 192.168.3.124
#  spring.redis.port: 6379
##  spring.redis.password：
#  spring.redis.pool.max-idle: 8
#  spring.redis.pool.min-idle: 0
#  spring.redis.pool.max-active: 8
#  spring.redis.pool.max-wait: -1
#  spring.redis.timeout: 5000

redis:
  spring:
    redis:
      database: 1
      host: 192.168.3.124
      port: 6379
      timeout: 5000


#配置日志
logging:
  #配置日志文件路径
  level:
    com.pb.news: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.mybatis: error
  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  file: log\myspringboot.log

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


canal:
  host: 127.0.0.1
  port: 11111
  destination: example
  username:
  password:

#canal:
#  host: 127.0.0.1
#  port: 11111
#  zkHost: 172.24.29.253:2181
#  destination: example
#  username: canal
#  password: E3619321C1A937C46A0D8BD1DAC39F93B27D4458
